config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users 


  get 'home/index'
  root 'home#index' 

  resources :clients do
    resources :projects 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #

      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin      
        can :manage, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :projects, dependent: :destroy 
   
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :project
  mount_uploader :attachimg, AttachmentUploader
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :client
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
   
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base    
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :authenticate_user! 
     load_and_authorize_resource
    def index
   	  @clients=Client.all
    end
     
    def show
     @client=Client.find(params[:id])     
    end 
    
    def new 
    	@client=Client.new
    end
    
    def create
      @client =Client.new(client_params)
      if @client.save
        redirect_to home_index_path
      else
        render 'new'
      end
    end

  

    def destroy
       @client = Client.find(params[:id])
       @client.destroy
       redirect_to clients_path, notice:  "The client #{@client.name} has been deleted."
    end

    
    private 
     def client_params
       params.require(:client).permit(:name, :email, :contact, :skills, :address)
     end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user! 

  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
   before_action :authenticate_user! 
   
   def index
      @client=Client.find(params[:client_id])                                                                                                                                                                                                                                                              
      @projects=@client.projects.all
   end

   def new
   	@client=Client.find(params[:client_id])
      @project=Project.new
   end
   
   def edit
     @client = Client.find(params[:client_id])
     @project = @client.projects.find(params[:id])
   end
   
   def create
   	@client=Client.find(params[:client_id])
   	@project = @client.projects.new(project_params)
   	if @project.save
        redirect_to client_path(@client)
      end 
   end

   def update
     @client = Client.find(params[:client_id])
     @project= @client.projects(params[:id])
     if @project.update(project_params)
        redirect_to client_path(@client), notice: "The project #{@project.title} has been uploaded."
     else
        render 'edit'
     end
   end

   def destroy
      @client=Client.find(params[:client_id])
      @project=@client.projects.find(params[:id])
      @project.destroy
      redirect_to client_path(@client) 
    end
      
   private
      def project_params
        params.require(:project).permit(:title, :description, :gems, images_attributes:[:id, :attachimg, :_destroy])
      end  
end
                                                    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/clients/index.html.erb
 <table class="table">
   <tr>
     <th>Name</th>
     <th>Email</th>
     <th>Contact</th>
     <th>Skills</th>
     <th>Address</th>
   </tr>

   <% @clients.each do|client| %>
     <tr>
       <td><%= client.name %></td> 
       <td><%= client.email%>
       <td><%= client.contact %>
       <td><%= client.skills %></td>
       <td><%= client.address %></td>
       <td><%= link_to 'show', client_path(client) %></td>
       <td><%= link_to 'Destroy', client_path(client), method: :delete,
              data: { confirm: 'Are you sure?' }  %></td>
       <td><%= link_to  'create project', new_client_project_path(client) %></td>
     </tr> 
   <% end %>
 </table>





<%= link_to 'Back', home_index_path %>

app/views/clients/new.html.erb
<%= form_for @client do |f| %>
 
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@client.errors.count, "error") %> prohibited
        this client from being saved:
      </h2>
      <ul>
        <% @client.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="col-lg-10">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control " %>
  </div>
   <br>
 <div  class="col-lg-10">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control col-6" %>
  </div>
  
 <div  class="col-sm-10">
    <%= f.label :contact %><br>
    <%= f.text_field :contact,class: "form-control " %>
 </div>
  
  <div class="col-xs-10">
   
    <%= f.label :skills %><br>
    <%#= f.text_field :skills, 'data-role' => 'tagsinput',class: "form-control", id: "demo" %>
    <%= f.text_field :skills,  id: "demo1" %>

  </div>

  <div  class="col-sm-10">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control " %>
  </div>
  <br>
  <div class="col-sm-10">
    <%= f.submit  class: "btn btn-default" %>
  </div>
 
<% end %>
<br>
<div class="col-lg-6">
<%= link_to 'Back', home_index_path, class: "btn btn-default" %>
</div>

app/views/clients/show.html.erb
<strong>Name:</strong>
<%= @client.name %>
<br>
<h1>Projects</h1>
<table class="table">
   <tr>
     <th>Title</th>
     <th>Description</th>
     <th>Gems</th>
     <th>Image</th>
   </tr>

   <% @client.projects.each do|project| %>
     <tr>
       <td><%= project.title %></td> 
       <td><%= raw(project.description) %></td>
       <td><%= project.gems.join(", ")  %></td>
       <td><%= image_tag (project.attachment) ,:size => "50x50"%></td>
     </tr> 
   <% end %>
 </table>
<h3>Add Projects</h3>



  

app/views/home/index.html.erb
<h1>Welcome </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Newapp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body id="screen-selection">

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Newapp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          <% if user_signed_in? %>
           <% if  current_user.has_role? :admin %>
            <li><%= link_to "Add Client", new_client_path  %></li>
           <%end%>  
           <% if  current_user.has_role? :admin %>
            <li><%= link_to "Client List", clients_path  %></li>
           <%end%> 
          <% end %> 
            <li><%#= link_to "Project List" %></li>
          </ul>
           <% if user_signed_in? %>
              <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.email %>
                  <span class="caret"></span></a>
                   <ul class="dropdown-menu">
                     <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
                   </ul>
                </li>
              </ul>
            <% end %>

        </div>
      </div>
    </div>
     
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
       <!--  <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%#= link_to "Link1", "/path1"  %></li>
              <li><%#= link_to "Link2", "/path2"  %></li>
              <li><%#= link_to "Link3", "/path3"  %></li>
            </ul>
           
          </div><!--/.well -->
        <!--/div> --><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :url=> client_projects_path(@client) do |f| %>
   <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
   </div>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => 'ckeditor' %>
  </p>

  <div  class="form-group">
    <%= f.label :gems %><br>
    <%= f.text_field :gems, 'data-role' => 'tagsinput',class: "form-control" %>
  </div>

   <p> 
      <%#= f.fields_for :images do |image| %>
        <%#= render 'image_fields' %>
      <%# end %> 
      <div class='links'>
      <%#= link_to_add_association 'add image', f, :images %>
    </div>   
   </p>
    <div>
     <%= f.submit 'submit', class: "btn btn-primary" %>
    </div>  
<% end %>

app/views/projects/_image_fields.html.erb
<div class='nested-fields'>
    <div class="form-group">
     <%= f.file_field  :attachimg,  class: "form-control" %>
    </div>
    <%= link_to_remove_association "remove image", f %>
 </div>

app/views/projects/edit.html.erb
<h1>Update Project</h1>
<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<table class="table">
   <tr>
     <th>Title</th>
     <th>Description</th>
     <th>Gems</th>
     <th>Image</th>
   </tr>

   <% @projects.each do|project| %>
     <tr>
       <td><%= project.title %></td> 
       <td><%= raw(project.description) %></td>
       <td><%= project.gems %></td>
       <td>
         <% project.images.each do |image| %>
           <%=  image_tag (image.attachimg), :size => "50x50"  %>
         <% end %>
        </td>
       <td><%= link_to 'edit', edit_client_project_path(@client, project)%></td>
       <td><%= link_to 'Destroy', [project.client, project], method: :delete,
              data: { confirm: 'Are you sure?' }  %></td>
     </tr> 
   <% end %>
 </table>

app/views/projects/new.html.erb
<%= form_for @project, :url=> client_projects_path(@client) do |f| %>
   <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
   </div>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => 'ckeditor' %>
  </p>

  <p>
    <%= f.label :gems %><br>
    <%= f.text_field :gems, 'data-role' => 'tagsinput', width: '400px' %>
  </p>

   <div class="form-group">
     <%= f.file_field :attachment, class: "form-control" %>
   </div>

   <p> 
      <%= f.fields_for :images do |image| %>
        <%= render 'image_fields' %>
      <% end %> 
      <div class='links'>
      <%= link_to_add_association 'add image', f, :images %>
    </div>   
   </p>
    <div>
     <%= f.submit 'submit', class: "btn btn-primary" %>
    </div>  
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>